--**********************************************************************************************--
-- Title: Assigment08 - Final Milestone 03 Task 01
-- Author: Justin Tran
-- Desc: This file is inserting data about into the database made in a previous assignment
-- Change Log: When,Who,What
-- 2020-03-10,Justin Tran,Created File
--***********************************************************************************************--

insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Eimbee', '940-433-9463', '137 Artisan Alley', 'Wichita Falls', 'TX', '76305');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Twitterwire', '502-882-0282', '6869 Randy Center', 'Louisville', 'KY', '40205');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Dynabox', '727-187-7363', '00 Steensland Place', 'Clearwater', 'FL', '34620');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Gigaclub', '386-951-7012', '73335 Grover Plaza', 'Daytona Beach', 'FL', '32128');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Yombu', '919-713-0509', '4 Green Avenue', 'Raleigh', 'NC', '27658');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Gabtune', '803-120-9361', '7 Novick Trail', 'Columbia', 'SC', '29220');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Thoughtbridge', '304-941-6754', '5 Buell Alley', 'Charleston', 'WV', '25321');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Twitterlist', '214-171-5817', '993 Service Terrace', 'Dallas', 'TX', '75392');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Twinder', '517-569-4606', '3 Esker Hill', 'Lansing', 'MI', '48919');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Zoovu', '907-988-4880', '61 Hagan Hill', 'Anchorage', 'AK', '99507');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Muxo', '602-363-0402', '42 High Crossing Junction', 'Phoenix', 'AZ', '85099');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Katz', '212-527-5445', '93796 Lunder Trail', 'New York City', 'NY', '10292');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Edgewire', '336-400-6736', '6 Kipling Road', 'Winston Salem', 'NC', '27157');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Buzzster', '804-712-7005', '94 Upham Pass', 'Richmond', 'VA', '23260');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Wikivu', '559-879-6561', '06883 American Alley', 'Modesto', 'CA', '95354');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Flipbug', '408-774-2904', '02 Mcbride Pass', 'San Jose', 'CA', '95150');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Twitterlister', '832-547-9438', '6 Elmside Terrace', 'Houston', 'TX', '77080');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Kazio', '203-164-0387', '47289 Carioca Way', 'Waterbury', 'CT', '06705');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Snicks', '914-155-4360', '5 Sheridan Center', 'Yonkers', 'NY', '10705');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Feedbug', '520-420-4836', '5 Westerfield Way', 'Tucson', 'AZ', '85715');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Yambee', '202-882-5614', '561 Maryland Street', 'Washington', 'DC', '20520');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Devbug', '918-728-9750', '2674 Monica Plaza', 'Tulsa', 'OK', '74108');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Ntag', '203-834-1898', '77 Elgar Court', 'New Haven', 'CT', '06533');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Fadeo', '209-780-3049', '965 Fairfield Place', 'Fresno', 'CA', '93721');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZipCode) values ('Yacero', '727-511-0779', '10396 Sage Parkway', 'Saint Petersburg', 'FL', '33742');

insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Hans', 'Fould', '702-752-1857', '158 Ryan Pass', 'Las Vegas', 'NV', '89145');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Gerard', 'Father', '973-771-2209', '8485 Mcbride Place', 'Newark', 'NJ', '07104');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Haven', 'De La Cote', '202-503-2612', '23910 David Circle', 'Washington', 'DC', '20046');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Udell', 'Houliston', '512-126-1024', '108 Logan Way', 'Austin', 'TX', '78744');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Bobbye', 'Gerold', '214-722-5726', '6 Mosinee Point', 'Garland', 'TX', '75049');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Thatch', 'Linge', '979-110-0465', '61590 Luster Alley', 'Bryan', 'TX', '77806');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Rickey', 'Pigne', '415-179-0163', '8258 Waubesa Place', 'San Francisco', 'CA', '94116');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Darryl', 'Britt', '682-959-7142', '4974 Sutteridge Road', 'Fort Worth', 'TX', '76178');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Monti', 'McEniry', '701-900-3524', '5827 Grasskamp Place', 'Grand Forks', 'ND', '58207');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Leonard', 'Grancher', '305-848-7612', '230 Lawn Way', 'Miami', 'FL', '33185');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Grete', 'Maidment', '203-460-6538', '613 Declaration Road', 'New Haven', 'CT', '06520');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Caroljean', 'Deniske', '316-220-5935', '6 Service Parkway', 'Wichita', 'KS', '67215');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Norean', 'Izachik', '904-744-2619', '127 Anderson Pass', 'Jacksonville', 'FL', '32259');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Gregoire', 'Ridolfi', '941-196-3116', '508 Roth Plaza', 'Orlando', 'FL', '32819');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Correy', 'McInnes', '817-738-5247', '858 Hollow Ridge Road', 'Fort Worth', 'TX', '76110');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Xena', 'Goodsir', '865-532-0060', '564 Texas Lane', 'Knoxville', 'TN', '37924');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Fidelity', 'Grgic', '210-288-5786', '0 Mandrake Terrace', 'San Antonio', 'TX', '78278');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Christopher', 'Grishelyov', '212-109-0856', '81 Mayer Hill', 'New York City', 'NY', '10115');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Reuven', 'Spir', '320-988-7169', '86 Darwin Junction', 'Saint Cloud', 'MN', '56372');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Lanny', 'Latham', '216-794-4195', '14917 Old Gate Way', 'Cleveland', 'OH', '44118');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Murray', 'Keasley', '540-495-7149', '648 Granby Center', 'Roanoke', 'VA', '24009');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Felike', 'Dalton', '307-777-6437', '0 Pennsylvania Hill', 'Cheyenne', 'WY', '82007');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Isa', 'Kreutzer', '719-820-5802', '05 Lighthouse Bay Parkway', 'Pueblo', 'CO', '81005');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Prudy', 'Lemerle', '832-339-9118', '0 Ridgeway Alley', 'Houston', 'TX', '77065');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Corella', 'Reilingen', '971-336-7947', '7 Barnett Junction', 'Portland', 'OR', '97271');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Chad', 'Waadenburg', '915-496-6888', '4676 Schurz Lane', 'El Paso', 'TX', '88546');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Aubrie', 'Schwaiger', '260-603-3799', '4 Mesta Street', 'Fort Wayne', 'IN', '46852');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Polly', 'Middleton', '813-163-2056', '762 Union Terrace', 'Tampa', 'FL', '33647');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Emyle', 'Willisch', '318-609-4411', '6 Oneill Court', 'Shreveport', 'LA', '71166');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Christoffer', 'Sidney', '512-472-6792', '60813 Banding Crossing', 'Austin', 'TX', '78789');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Pam', 'Gostall', '239-199-3805', '46722 Monument Drive', 'Naples', 'FL', '34114');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Harcourt', 'Boller', '214-363-2389', '2 Sugar Point', 'Dallas', 'TX', '75310');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Westbrook', 'Drew-Clifton', '240-934-5928', '40066 Caliangt Hill', 'Frederick', 'MD', '21705');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Nerte', 'Chedzoy', '608-137-9046', '84331 Northridge Court', 'Madison', 'WI', '53716');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Johan', 'Snellman', '717-945-0426', '169 Columbus Road', 'Harrisburg', 'PA', '17126');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Duffie', 'Extance', '434-681-5769', '8 Chive Center', 'Lynchburg', 'VA', '24515');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Akim', 'Haxbie', '509-696-6833', '7 Kinsman Point', 'Spokane', 'WA', '99252');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Miran', 'Rummings', '520-377-1504', '16 Maywood Street', 'Tucson', 'AZ', '85748');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Fawne', 'Skalls', '225-345-9688', '40916 Blue Bill Park Street', 'Baton Rouge', 'LA', '70805');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Beulah', 'Gianasi', '412-520-1611', '9159 Raven Lane', 'Pittsburgh', 'PA', '15235');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Larine', 'Stones', '915-780-3174', '09224 Dakota Way', 'El Paso', 'TX', '79994');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Ewan', 'Hornung', '419-523-5407', '69 Crownhardt Center', 'Toledo', 'OH', '43635');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Shelbi', 'Newlan', '402-333-0300', '6 Summer Ridge Drive', 'Lincoln', 'NE', '68510');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Tabbatha', 'Mullarkey', '225-168-1867', '56827 Orin Trail', 'Baton Rouge', 'LA', '70826');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Birgit', 'Barrick', '405-919-2242', '98030 Burning Wood Hill', 'Oklahoma City', 'OK', '73142');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Frances', 'Ehrat', '803-984-1337', '18375 Duke Court', 'Columbia', 'SC', '29225');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Amelia', 'Mulvenna', '808-514-4160', '78 International Avenue', 'Honolulu', 'HI', '96840');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Kala', 'Raun', '813-147-6199', '7091 Chinook Parkway', 'Tampa', 'FL', '33620');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Adolphe', 'Puve', '206-376-2533', '28 Quincy Street', 'Seattle', 'WA', '98195');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZipCode) values ('Reinald', 'Axby', '915-681-6551', '51 Saint Paul Road', 'El Paso', 'TX', '88541');

insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Kean', 'McRill', '646-658-4049', '5 Browning Street', 'New York City', 'NY', '10009');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Marysa', 'Mockett', '361-142-3251', '68 Farwell Drive', 'Corpus Christi', 'TX', '78470');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Bobette', 'Simeon', '423-516-5461', '67264 Darwin Place', 'Chattanooga', 'TN', '37450');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Tremain', 'Berick', '571-881-2648', '017 8th Park', 'Merrifield', 'VA', '22119');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Kellia', 'Doonican', '915-332-5155', '39604 Nevada Drive', 'El Paso', 'TX', '79905');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Buiron', 'Clampe', '719-484-2537', '17 Pankratz Alley', 'Colorado Springs', 'CO', '80935');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Carolyne', 'Vinson', '585-999-4844', '5 Heath Plaza', 'Rochester', 'NY', '14639');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Ruby', 'Crock', '213-150-5673', '605 Melrose Drive', 'North Hollywood', 'CA', '91616');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Roxanne', 'Kellitt', '203-987-8558', '0 Hanson Alley', 'New Haven', 'CT', '06510');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Faustine', 'Bellin', '410-451-0375', '73 Grover Place', 'Baltimore', 'MD', '21216');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Mathian', 'Hargraves', '404-857-1232', '8747 Express Trail', 'Atlanta', 'GA', '30375');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Romy', 'Kuhl', '717-628-5812', '78766 Nevada Parkway', 'Lancaster', 'PA', '17605');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Farra', 'Nockells', '316-101-2536', '52689 Burrows Terrace', 'Wichita', 'KS', '67205');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Jodi', 'Inger', '501-343-9516', '32 Manitowish Court', 'Little Rock', 'AR', '72209');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Merrill', 'Antoniou', '617-693-2585', '3010 Homewood Circle', 'Boston', 'MA', '02109');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Meris', 'McIver', '510-677-5226', '121 Nevada Crossing', 'Richmond', 'CA', '94807');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Rosemaria', 'Bothbie', '305-382-8825', '63 Ronald Regan Trail', 'Miami', 'FL', '33175');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Evonne', 'Speedy', '646-215-7228', '7969 Arapahoe Drive', 'New York City', 'NY', '10060');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Ermanno', 'Piggott', '281-821-2045', '2100 Golden Leaf Court', 'Houston', 'TX', '77080');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Aldo', 'Ingarfill', '571-589-0419', '25125 Graceland Pass', 'Springfield', 'VA', '22156');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Ingrid', 'McCluney', '714-877-2802', '091 Cordelia Avenue', 'Garden Grove', 'CA', '92645');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Hanna', 'Gibling', '816-727-1058', '562 Dexter Circle', 'Kansas City', 'MO', '64160');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Maud', 'Stockey', '813-412-8609', '0 Sauthoff Place', 'Tampa', 'FL', '33661');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Elsa', 'Dines', '512-108-6535', '3984 Norway Maple Hill', 'Austin', 'TX', '78783');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Corrine', 'Semeniuk', '786-518-5708', '143 Ridge Oak Street', 'Miami', 'FL', '33111');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Dav', 'Carlon', '509-289-7255', '4 Katie Avenue', 'Yakima', 'WA', '98907');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Kellina', 'Coo', '415-538-1955', '9 Springview Center', 'San Francisco', 'CA', '94121');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Cassie', 'Snelle', '954-164-8252', '98999 Upham Center', 'Fort Lauderdale', 'FL', '33325');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Nannette', 'Son', '706-288-0925', '257 Loftsgordon Point', 'Athens', 'GA', '30610');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Angelle', 'L''Episcopi', '760-304-6892', '15 West Terrace', 'Escondido', 'CA', '92030');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Kathye', 'Kimberley', '602-382-4201', '79114 Northwestern Plaza', 'Phoenix', 'AZ', '85015');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Alexandro', 'Aharoni', '616-637-7317', '67 Stoughton Terrace', 'Grand Rapids', 'MI', '49560');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Tierney', 'Hubbucke', '952-934-3705', '9 New Castle Circle', 'Maple Plain', 'MN', '55579');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Bartlet', 'Bodd', '410-457-2873', '99728 Parkside Hill', 'Baltimore', 'MD', '21290');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Lance', 'Kubacek', '646-405-4910', '0 Transport Street', 'New York City', 'NY', '10039');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Kimbell', 'Bahlmann', '404-919-1844', '684 Autumn Leaf Pass', 'Atlanta', 'GA', '31132');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Rafaello', 'Chinery', '915-912-0218', '3623 Fairfield Crossing', 'El Paso', 'TX', '79950');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Stefa', 'Munn', '402-202-8911', '0 Briar Crest Center', 'Lincoln', 'NE', '68524');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Tabb', 'Eskrick', '602-863-3546', '45 Susan Parkway', 'Phoenix', 'AZ', '85067');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Selie', 'Vidgeon', '337-954-3890', '29 Green Ridge Court', 'Lafayette', 'LA', '70505');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Bennett', 'Hamfleet', '801-336-7015', '2041 Del Sol Crossing', 'Salt Lake City', 'UT', '84140');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Roobbie', 'Lambal', '337-246-8140', '4 Emmet Avenue', 'Lafayette', 'LA', '70593');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Shurlocke', 'Coppen', '828-297-0280', '6 Talmadge Road', 'Asheville', 'NC', '28815');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Noah', 'Wilkison', '859-429-6863', '87 Lakeland Road', 'Lexington', 'KY', '40586');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Wilmette', 'Lubman', '818-216-8716', '16 Karstens Court', 'Burbank', 'CA', '91505');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Jammie', 'Burnard', '414-182-5074', '72398 Eagan Street', 'Milwaukee', 'WI', '53263');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Linus', 'Killingworth', '814-705-5504', '7 Petterle Point', 'Erie', 'PA', '16522');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Pam', 'Rizon', '985-878-0124', '5 Blackbird Way', 'New Orleans', 'LA', '70124');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Susan', 'Morhall', '724-823-1513', '2472 Scofield Center', 'New Castle', 'PA', '16107');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZipCode) values ('Brittan', 'Spitaro', '520-188-2095', '1376 Jana Point', 'Prescott', 'AZ', '86305');

insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-21 16:06:55', 2, 16, 12);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-03-10 05:39:58', 3, 28, 7);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2020-06-24 22:03:16', 4, 25, 10);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2020-01-26 01:47:09', 5, 4, 7);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-21 19:37:15', 6, 11, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2015-12-13 10:50:41', 7, 5, 11);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-05-08 15:46:41', 8, 50, 9);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-10-04 01:27:14', 9, 45, 3);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-29 08:04:34', 10, 33, 7);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2014-09-10 14:36:46', 11, 10, 21);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-02-19 05:15:43', 12, 10, 24);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-21 10:47:46', 13, 7, 10);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2012-01-28 05:43:24', 14, 48, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2013-11-03 16:31:22', 15, 44, 19);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2015-11-07 23:31:28', 16, 37, 10);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-01 12:54:05', 17, 10, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-09 03:51:24', 18, 48, 22);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-04-25 22:14:24', 19, 41, 12);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2015-01-22 23:54:51', 20, 18, 23);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2011-06-17 04:25:37', 21, 6, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2012-10-10 14:02:59', 22, 51, 14);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2011-08-06 13:58:41', 23, 6, 16);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2013-01-20 18:23:34', 24, 45, 15);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-09-19 10:06:26', 25, 17, 11);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-10-23 22:15:26', 26, 30, 24);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-11-20 11:43:36', 27, 23, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2015-07-30 01:11:33', 28, 17, 7);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-05-01 22:26:44', 29, 46, 12);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-20 11:23:23', 30, 31, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2011-03-20 05:51:35', 31, 37, 19);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-29 01:33:21', 32, 28, 26);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2014-07-20 07:20:57', 33, 27, 5);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-13 01:03:37', 34, 2, 5);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2010-08-04 20:07:26', 35, 42, 4);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2015-08-10 04:05:36', 36, 46, 5);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2010-10-27 21:08:01', 37, 18, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-06-13 13:00:27', 38, 14, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-10-28 10:19:02', 39, 29, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-06-22 20:04:33', 40, 13, 12);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-08-18 21:43:07', 41, 29, 18);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2011-10-27 21:58:29', 42, 48, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-09-01 17:36:22', 43, 17, 14);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-04-02 03:25:07', 44, 43, 22);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-03-13 19:54:04', 45, 49, 25);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2010-03-29 11:59:59', 46, 12, 26);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2016-09-22 14:29:12', 47, 41, 15);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2013-11-17 23:55:08', 48, 22, 6);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2010-08-01 10:14:38', 49, 46, 20);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2017-07-01 18:00:04', 50, 28, 14);
insert into Appointments (AppointmentDateTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2011-04-01 20:39:07', 51, 34, 21);

-- NOTE: All data was generated by mockaroo.com
